version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: baseNestjs
      POSTGRES_PASSWORD: 241299
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'