version: 2.1

jobs:
  install_packages:
    docker:
      - image: cimg/node:12.18-browsers
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b2:3b:fa:32:ac:6f:c4:05:78:da:69:0f:0e:e4:da:45"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/Air-travel-api && echo Success access && sudo git pull && sudo npm run build && sudo pm2 update"

workflows:
  test_my_app:
    jobs:
      - install_packages
      - deploy:
          requires:
            - install_packages
          filters:
            branches:
              only: master # only deploy on the master branch
