version: 2.1
jobs:
  lint/tests:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - restore-cache:
        keys:
          - node-deps-v1-{{ .Branch }}-{{ checksum "~/Air-travel-api/package-lock.json" }}
      - run:
        name: Install dependencies
        command:
          npm install
      - run:
        name: Test lint
        command:
          npm run lint
      - save_cache:
        paths:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "~/Air-travel-api/package-lock.json" }}
          paths:
            - ~/.npm
workflows:
  node-tests:
    jobs:
      - lint/tests
