version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:12.18-browsers
        auth:
            username: chuotcona123
            password: qweasdzxc2412
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
  lint:
    docker:
      - image: cimg/node:12.18-browsers
        auth:
            username: chuotcona123
            password: qweasdzxc2412
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Run lint
          command: npm run lint


workflows:
  test_my_app:
    jobs:
      - install
      - lint:
        requires:
          - install